---
title: "Map functional richness"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(oharac)
oharac::setup()
source(here('fb_slb_fxns.R'))

```

# Summary

Apply functional groups to AquaMaps species distributions to identify patterns of functional richness.  Look at:

* how many functional groups are represented in each pixel?
* for each functional group, what patterns of species richness are observed?

Note we are not yet looking at vulnerability or impacts...

# Data

See individual trait scripts.

# Methods

``` {r}
spp_fxn_groups <- read_csv(here('_data/functional_groups_from_traits.csv'))

spp_info <- get_am_spp_info()

spp_by_gp <- spp_info %>% 
  dplyr::select(am_sid, sciname) %>%
  inner_join(spp_fxn_groups, by = c('sciname' = 'species')) ### 18285 spp matched in fxn gps

spp_nomatch <- spp_info %>% 
  anti_join(spp_fxn_groups, by = c('sciname' = 'species')) ### 15233 obs not matched in fxn gps
spp_nomatch_all <- spp_info %>%
  anti_join(get_worms(), by = c('sciname' = 'species')) ### 5051 obs not matched at all
### rectify the AquaMaps species names according to WoRMS to improve matches!!!
```


``` {r}
spp_cells <- get_am_spp_cells(occurcells_cut = 10, prob_cut = 0.5)

fxn_cells <- spp_by_gp %>%
  inner_join(spp_cells, by = 'am_sid')

fxn_count <- fxn_cells %>%
  group_by(loiczid) %>%
  summarize(n_fxn_p = n_distinct(p_group),
            n_fxn_k = n_distinct(k_group), .groups = 'drop')

fxn_p_spp_count <- fxn_cells %>%
  group_by(p_group, loiczid) %>%
  summarize(n_fxn_spp = n_distinct(am_sid), 
            .groups = 'drop')

```

``` {r plot fxn_gps}
rast_base <- get_hcaf_rast()

fxn_count_rast <- map_to_hcaf(fxn_count, which = 'n_fxn_p')
plot(fxn_count_rast, col = hcl.colors(20), main = 'Functional groups (count)')
for(gp in sort(unique(fxn_p_spp_count$p_group))) { ### gp <- 'B'
  gp_df <- fxn_p_spp_count %>%
    filter(p_group == gp)

  gp_spp_rast <- map_to_hcaf(gp_df, which = 'n_fxn_spp', xfm = log10)
  plot(gp_spp_rast, col = hcl.colors(20), main = sprintf('log10(spp count) in functional group %s', gp))
}
```
