---
title: "Set up stressors"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(oharac)
oharac::setup()
source(here('fb_slb_fxns.R'))

```

# Summary

Read in 2013 stressor intensity maps and aggregate/reproject for use with AquaMaps resolution

# Data

Stressor intensity rasters at 10 km Mollweide resolution from O'Hara et al. (2021)

# Methods

Read in stressor layers from 10 km resolution from BD/CHI project; then reproject into .5° resolution.

```{r}
dir_str_10km  <- '~/git-annex/bd_chi/layers/stressors_10km'
dir_str_0.5  <- 

f_df <- data.frame(f = list.files(dir_str_10km, recursive = TRUE, full.names = TRUE)) %>%
  mutate(str = str_remove(basename(f), '_[0-9]{4}_rescaled.+'),
         year = str_extract(basename(f), '[0-9]{4}') %>% as.integer()) %>%
  group_by(str) %>%
  filter(year == max(year))
```

``` {r read and reproject}
r_base <- get_hcaf_rast()

out_stem <- here('_spatial/stressors_hcaf/%s_%s_hcaf.tif')
for(i in 1:nrow(f_df)) {
  ### i <- 15
  s <- f_df$str[i]
  y <- f_df$year[i]
  f <- f_df$f[i]
  r <- raster(f)
  r_reproj <- projectRaster(r, r_base, method = 'bilinear')
  writeRaster(r_reproj, sprintf(out_stem, s, y), overwrite = TRUE)
}
```



