---
title: "Calculate spp ranges from rangemaps"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(oharac) ### remotes::install_github('oharac/oharac')
library(tidyverse)
library(here)
source(here('common_fxns.R'))

```

# Summary

Read in the various range maps; for each, summarize to total ocean area.  Save as csv of species name, source (AquaMaps or IUCN), and coastal (i.e., continental shelf) and total range.

# Methods

## Identify species map files and sources

```{r}
map_fs <- list.files(here_anx('spp_maps_mol'), pattern = '_spp_mol_', full.names = TRUE)
iucn_to_name <- read_csv(here('_data/iucn_spp/iucn_to_worms_match.csv')) %>%
  select(iucn_sid, sciname = worms_name)
maps_df <- data.frame(f = map_fs) %>%
  mutate(src = basename(f) %>% str_remove('_.+'),
         id  = basename(f) %>% str_remove_all('.+spp_mol_|.csv'),
         iucn_sid = as.numeric(id)) %>%
  left_join(iucn_to_name, by = 'iucn_sid') %>%
  mutate(sciname = ifelse(is.na(sciname), str_replace_all(id, '_', ' '), sciname)) %>%
  arrange(sciname)
  
```

## Loop over files, calc total and coastal range

```{r}
ocean_a_rast <- raster(here('_spatial/ocean_area_mol.tif'))
coastal_rast <- raster(here('_spatial/bathy_mol_neritic.tif'))
ocean_a_df <- data.frame(
  ocean_a_km2 = values(ocean_a_rast) * 100,
  coast_a_km2 = values(mask(ocean_a_rast, coastal_rast)) * 100,
  cell_id = 1:ncell(ocean_a_rast)) %>%
  filter(!is.na(ocean_a_km2))

calc_range <- function(f) {
  src <- str_remove(basename(f), '_.+')
  spp_range <- data.table::fread(f)
  if(src == 'am') {
    spp_range <- spp_range %>%
      filter(prob >= .5)
  } else {
    spp_range <- spp_range %>%
      filter(presence != 5)
  }
  spp_range <- spp_range %>%
    oharac::dt_join(ocean_a_df, by = 'cell_id', type = 'left') %>%
    summarize(range_tot_km2 = sum(ocean_a_km2, na.rm = TRUE),
              range_cst_km2 = sum(coast_a_km2, na.rm = TRUE))
  return(spp_range)
}
```

```{r}
out_f <- here('_data/spp_ranges.csv')

if(!file.exists(out_f)) {
  range_list <- parallel::mclapply(maps_df$f, mc.cores = 24,
                                   ### f <- maps_df$f[1]
                                   FUN = function(f) calc_range(f))
  
  range_df <- range_list %>%
    setNames(maps_df$f) %>%
    data.table::rbindlist(idcol = 'f')
  
  out_df <- maps_df %>%
    left_join(range_df, by = 'f') %>%
    dplyr::select(-f, -id)
  
  write_csv(out_df, out_f)
}
```

